[package]
name = "minecraft_packets"
version = "0.1.0"
edition = "2021"

[dependencies]
minecraft_protocol = { path = "../minecraft_protocol" }
thiserror = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
rand = "0.9.0"
